# include <iostream>
# include <fstream>
# include <vector>
# include <string>

using namespace std;
 
vector<vector<long long>> add_vectors(const vector<vector<long long>> &a, const vector<vector<long long>> &b) { // element-wise addition
    long long n = a.size(), m = a[0].size();
    vector<vector<long long>> result(n, vector<long long>(m, 0));
    for (long long i = 0; i < n; i++) {
        for (long long j = 0; j < m; j++) {
            result[i][j] = a[i][j] + b[i][j];
        }
    }
    return result;
}

bool match_vectors(const vector<vector<long long>> &a, const vector<vector<long long>> &b) { // element-wise comparison
    if (a.size() != b.size() || a[0].size() != b[0].size()) return false;
    long long n = a.size(), m = a[0].size();
    for (long long i = 0; i < n; i++) {
        for (long long j = 0; j < m; j++) {
            if (a[i][j] != b[i][j]) return false;
        }
    }
    return true;
}

void store_matrix(ofstream &ofs, const vector<vector<long long>> &mat) {
    long long n = mat.size(), m = mat[0].size();
    for (long long i = 0; i < n; i++) {
        for (long long j = 0; j < m; j++) {
            ofs << mat[i][j] << " ";
        }
        ofs << endl;
    }
    ofs << endl;
}

int main() {
    string query_file0 = "f1.txt", query_file1 = "f2.txt";
    string output_file0 = "data/output0.txt", output_file1 = "data/output1.txt";
    ifstream ifs0(query_file0), ifs1(query_file1);
    ifstream ofs0(output_file0), ofs1(output_file1);

    ofstream result_file("data/added.txt");

    long long n, m, k, q;
    ifs0 >> m >> n >> k >> q;
    ifs1 >> m >> n >> k >> q;
    vector<vector<long long>> u0(m, vector<long long>(k)), u1(m, vector<long long>(k)); // read u0 and u1
    for (long long i = 0; i < m; i++) {
        for (long long j = 0; j < k; j++) ofs0 >> u0[i][j];
    }
    for (long long i = 0; i < m; i++) {
        for (long long j = 0; j < k; j++) ofs1 >> u1[i][j];
    }
    vector<vector<long long>> u = add_vectors(u0, u1); // generate u = u0 + u1
    store_matrix(result_file, u);

    vector<vector<long long>> v0(n, vector<long long>(k)), v1(n, vector<long long>(k)); // read v0 and v1
    for (long long i = 0; i < n; i++) {
        for (long long j = 0; j < k; j++) ofs0 >> v0[i][j];
    }
    for (long long i = 0; i < n; i++) {
        for (long long j = 0; j < k; j++) ofs1 >> v1[i][j];
    }
    vector<vector<long long>> v = add_vectors(v0, v1); // generate v = v0 + v1
    store_matrix(result_file, v);

    for (long long p = 0; p < q; p++) {
        long long i;
        ifs0 >> i;
        ifs1 >> i;
        long long j0, j1;
        ifs0 >> j0;
        ifs1 >> j1;
        long long j = j0 + j1;
        std::cout << "i = " << i << ", j = " << j << std::endl;
        long long dot_product = 0;
        for (long long l = 0; l < k; l++) dot_product += u[i][l] * v[j][l];
        std::cout << "dot_product = " << dot_product << std::endl;
        std::cout<< "v * delta = ";
        for(int l = 0; l<k; l++) std::cout<< v[j][l]*(1 - dot_product) << " ";
        std::cout<< std::endl;
        for (long long l = 0; l < k; l++) v[j][l] += u[i][l]*(1 - dot_product); // update v[j] = v[j] + u[i]*(1 - dot_product(u[i], v[j]))

        std::cout << "u * delta = ";
        for (int l = 0; l < k; l++) std::cout << u[i][l]*(1 - dot_product) << " ";
        std::cout << std::endl;

        vector<vector<long long>> v0_new(n, vector<long long>(k, 0)), v1_new(n, vector<long long>(k, 0)); // read new v0 and v1 generated by p0 and p1
        for (long long x = 0; x < n; x++) {
            for (long long y = 0; y < k; y++) ofs0 >> v0_new[x][y];
        }
        for (long long x = 0; x < n; x++) {
            for (long long y = 0; y < k; y++) ofs1 >> v1_new[x][y];
        }
        vector<vector<long long>> v_new = add_vectors(v0_new, v1_new); // generate new v = new v0 + new v1
        result_file << "Result got:" << endl;
        store_matrix(result_file, v_new);
        result_file << "True result:" << endl;
        store_matrix(result_file, v);

        if (match_vectors(v, v_new)) { // check whether the expected answer is same or not
            cout << "Query " << p << ": PASS" << endl;
        } else {
            cout << "Query " << p << ": FAIL" << endl;
        }
    }
    return 0;
}
